#! /bin/bash
# generated by collect_git_add_recursively.sh
pushd $(dirname $0)       2> /dev/null

cd ..
git submodule update --init
git submodule update --init --recursive

util/git_checkout_submodules_head.sh



if test -d documentation/wiki ; then pushd documentation/wiki ; git remote add wiki-original ../wiki-vanilla/ ; popd; fi

popd       2> /dev/null

