#! /bin/bash
# generated by collect_git_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}





if test -d documentation/wiki ; then pushd documentation/wiki ; git remote add wiki-original ../wiki-vanilla/ ; popd; fi






register_remote documentation/wiki                                            65                                       git@github.com:65/d3.wiki.git                                                    $# $@
register_remote documentation/wiki                                            CmdrShaw                                 git@github.com:CmdrShaw/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            EdSimonoff                               git@github.com:EdSimonoff/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            GerHobbelt                               git@github.com:GerHobbelt/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            Greyz09                                  git@github.com:Greyz09/d3.wiki.git                                               $# $@
register_remote documentation/wiki                                            InfographicsJa                           git@github.com:InfographicsJa/d3.wiki.git                                        $# $@
register_remote documentation/wiki                                            MBallenger                               git@github.com:MBallenger/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            Moviri                                   git@github.com:Moviri/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            RoyLai                                   git@github.com:RoyLai/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            Yahasana                                 git@github.com:Yahasana/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            ZJONSSON                                 git@github.com:ZJONSSON/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            akwirick                                 git@github.com:akwirick/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            andrewdyates                             git@github.com:andrewdyates/d3.wiki.git                                          $# $@
register_remote documentation/wiki                                            aunalytics                               git@github.com:aunalytics/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            beacrea                                  git@github.com:beacrea/d3.wiki.git                                               $# $@
register_remote documentation/wiki                                            cruxi                                    git@github.com:cruxi/d3.wiki.git                                                 $# $@
register_remote documentation/wiki                                            daigo3                                   git@github.com:daigo3/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            djohnlewis                               git@github.com:djohnlewis/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            dother                                   git@github.com:dother/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            flyingoctopus                            git@github.com:flyingoctopus/d3.wiki.git                                         $# $@
register_remote documentation/wiki                                            fone4u                                   git@github.com:fone4u/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            gigadude                                 git@github.com:gigadude/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            gitnacho                                 git@github.com:gitnacho/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            gka                                      git@github.com:gka/d3.wiki.git                                                   $# $@
register_remote documentation/wiki                                            gollmann                                 git@github.com:gollmann/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            h98                                      git@github.com:h98/d3.wiki.git                                                   $# $@
register_remote documentation/wiki                                            jdk137                                   git@github.com:jdk137/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            jeyoor                                   git@github.com:jeyoor/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            jiangdapeng                              git@github.com:jiangdapeng/d3.wiki.git                                           $# $@
register_remote documentation/wiki                                            klettow                                  git@github.com:klettow/d3.wiki.git                                               $# $@
register_remote documentation/wiki                                            kumthekar                                git@github.com:kumthekar/d3.wiki.git                                             $# $@
register_remote documentation/wiki                                            lgrammatas                               git@github.com:lgrammatas/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            maplejan                                 git@github.com:maplejan/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            masbenx                                  git@github.com:masbenx/d3.wiki.git                                               $# $@
register_remote documentation/wiki                                            mbostock                                 git@github.com:mbostock/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            mbostock-original                        git@github.com:mbostock/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            mikeycgto                                git@github.com:mikeycgto/d3.wiki.git                                             $# $@
register_remote documentation/wiki                                            neopunisher                              git@github.com:neopunisher/d3.wiki.git                                           $# $@
register_remote documentation/wiki                                            peterboda                                git@github.com:peterboda/d3.wiki.git                                             $# $@
register_remote documentation/wiki                                            protez                                   git@github.com:protez/d3.wiki.git                                                $# $@
register_remote documentation/wiki                                            sebastianseilund                         git@github.com:sebastianseilund/d3.wiki.git                                      $# $@
register_remote documentation/wiki                                            seliopou                                 git@github.com:seliopou/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            silverasm                                git@github.com:silverasm/d3.wiki.git                                             $# $@
register_remote documentation/wiki                                            spmbt                                    git@github.com:spmbt/d3.wiki.git                                                 $# $@
register_remote documentation/wiki                                            webmonarch                               git@github.com:webmonarch/d3.wiki.git                                            $# $@
register_remote documentation/wiki                                            wiki-vanilla-original                    ../wiki-vanilla/                                                                 $# $@
register_remote documentation/wiki                                            zjohnsson                                git@github.com:ZJONSSON/d3.wiki.git                                              $# $@
register_remote documentation/wiki                                            zziuni                                   git@github.com:zziuni/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    65                                       git@github.com:65/d3.wiki.git                                                    $# $@
register_remote documentation/wiki-vanilla                                    CmdrShaw                                 git@github.com:CmdrShaw/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    EdSimonoff                               git@github.com:EdSimonoff/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    GerHobbelt                               git@github.com:GerHobbelt/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    Greyz09                                  git@github.com:Greyz09/d3.wiki.git                                               $# $@
register_remote documentation/wiki-vanilla                                    InfographicsJa                           git@github.com:InfographicsJa/d3.wiki.git                                        $# $@
register_remote documentation/wiki-vanilla                                    MBallenger                               git@github.com:MBallenger/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    Moviri                                   git@github.com:Moviri/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    RoyLai                                   git@github.com:RoyLai/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    Yahasana                                 git@github.com:Yahasana/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    ZJONSSON                                 git@github.com:ZJONSSON/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    akwirick                                 git@github.com:akwirick/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    andrewdyates                             git@github.com:andrewdyates/d3.wiki.git                                          $# $@
register_remote documentation/wiki-vanilla                                    aunalytics                               git@github.com:aunalytics/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    beacrea                                  git@github.com:beacrea/d3.wiki.git                                               $# $@
register_remote documentation/wiki-vanilla                                    cruxi                                    git@github.com:cruxi/d3.wiki.git                                                 $# $@
register_remote documentation/wiki-vanilla                                    daigo3                                   git@github.com:daigo3/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    djohnlewis                               git@github.com:djohnlewis/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    dother                                   git@github.com:dother/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    flyingoctopus                            git@github.com:flyingoctopus/d3.wiki.git                                         $# $@
register_remote documentation/wiki-vanilla                                    fone4u                                   git@github.com:fone4u/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    gigadude                                 git@github.com:gigadude/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    gitnacho                                 git@github.com:gitnacho/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    gka                                      git@github.com:gka/d3.wiki.git                                                   $# $@
register_remote documentation/wiki-vanilla                                    gollmann                                 git@github.com:gollmann/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    h98                                      git@github.com:h98/d3.wiki.git                                                   $# $@
register_remote documentation/wiki-vanilla                                    jdk137                                   git@github.com:jdk137/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    jeyoor                                   git@github.com:jeyoor/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    jiangdapeng                              git@github.com:jiangdapeng/d3.wiki.git                                           $# $@
register_remote documentation/wiki-vanilla                                    klettow                                  git@github.com:klettow/d3.wiki.git                                               $# $@
register_remote documentation/wiki-vanilla                                    kumthekar                                git@github.com:kumthekar/d3.wiki.git                                             $# $@
register_remote documentation/wiki-vanilla                                    lgrammatas                               git@github.com:lgrammatas/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    maplejan                                 git@github.com:maplejan/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    masbenx                                  git@github.com:masbenx/d3.wiki.git                                               $# $@
register_remote documentation/wiki-vanilla                                    mbostock                                 git@github.com:mbostock/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    mbostock-original                        git@github.com:mbostock/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    mikeycgto                                git@github.com:mikeycgto/d3.wiki.git                                             $# $@
register_remote documentation/wiki-vanilla                                    neopunisher                              git@github.com:neopunisher/d3.wiki.git                                           $# $@
register_remote documentation/wiki-vanilla                                    peterboda                                git@github.com:peterboda/d3.wiki.git                                             $# $@
register_remote documentation/wiki-vanilla                                    protez                                   git@github.com:protez/d3.wiki.git                                                $# $@
register_remote documentation/wiki-vanilla                                    sebastianseilund                         git@github.com:sebastianseilund/d3.wiki.git                                      $# $@
register_remote documentation/wiki-vanilla                                    seliopou                                 git@github.com:seliopou/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    silverasm                                git@github.com:silverasm/d3.wiki.git                                             $# $@
register_remote documentation/wiki-vanilla                                    spmbt                                    git@github.com:spmbt/d3.wiki.git                                                 $# $@
register_remote documentation/wiki-vanilla                                    webmonarch                               git@github.com:webmonarch/d3.wiki.git                                            $# $@
register_remote documentation/wiki-vanilla                                    zjohnsson                                git@github.com:ZJONSSON/d3.wiki.git                                              $# $@
register_remote documentation/wiki-vanilla                                    zziuni                                   git@github.com:zziuni/d3.wiki.git                                                $# $@



popd                                                                            2> /dev/null   > /dev/null

